# Generated by Django 5.1 on 2024-09-15 12:35

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_thuong_xuyen1', models.FloatField(blank=True)),
                ('diem_thuong_xuyen2', models.FloatField(blank=True)),
                ('diem_thuong_xuyen3', models.FloatField(blank=True)),
                ('diem_thuong_xuyen4', models.FloatField(blank=True)),
                ('diem_giua_ki', models.FloatField(blank=True)),
                ('diem_cuoi_ki', models.FloatField(blank=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subject', models.CharField(max_length=200)),
                ('is_boy', models.BooleanField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('is_boy', models.BooleanField()),
                ('math', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='Du_An.mainsubject')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('children', models.ManyToManyField(related_name='parent', to='Du_An.student')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('students', models.ManyToManyField(blank=True, related_name='Class', to='Du_An.student')),
                ('form_teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_class', to='Du_An.teacher')),
                ('math_teacher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='math_teaching_class', to='Du_An.teacher')),
            ],
        ),
    ]
