# Generated by Django 5.1 on 2024-09-18 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Du_An', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='math_teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='math',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_boy',
        ),
        migrations.AddField(
            model_name='mainsubject',
            name='name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='full_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='main_subjects',
            field=models.ManyToManyField(related_name='student', to='Du_An.mainsubject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classroom', to='Du_An.student'),
        ),
        migrations.AlterField(
            model_name='mainsubject',
            name='diem_cuoi_ki',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mainsubject',
            name='diem_giua_ki',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mainsubject',
            name='diem_thuong_xuyen1',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mainsubject',
            name='diem_thuong_xuyen2',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mainsubject',
            name='diem_thuong_xuyen3',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mainsubject',
            name='diem_thuong_xuyen4',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.CreateModel(
            name='ClassSubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_classes', to='Du_An.teacher')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='Du_An.subject')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='subject_teachers',
            field=models.ManyToManyField(related_name='classroom', to='Du_An.classsubjectteacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(related_name='teachers', to='Du_An.subject'),
        ),
    ]
