# Generated by Django 5.1 on 2024-09-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Du_An', '0002_subject_remove_class_math_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
