# Generated by Django 5.1 on 2024-09-20 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Du_An', '0004_alter_class_form_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='form_teacher',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_class', to='Du_An.teacher'),
        ),
    ]
