# Generated by Django 5.1 on 2024-09-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Du_An', '0005_alter_class_form_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_thuong_xuyen1', models.FloatField(default=None, null=True)),
                ('diem_thuong_xuyen2', models.FloatField(default=None, null=True)),
                ('diem_giua_ki', models.FloatField(default=None, null=True)),
                ('diem_cuoi_ki', models.FloatField(default=None, null=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('monitor', 'Lớp trưởng'), ('academic', 'lớp phó học tập'), ('art', 'lớp phó văn thể mỹ'), ('labor', 'lớp phó lao động')], default='monitor', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact_information',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='second_subjects',
            field=models.ManyToManyField(related_name='student', to='Du_An.secondsubject'),
        ),
    ]
