# Generated by Django 5.1 on 2024-09-21 22:46

import Du_An.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Du_An', '0007_alter_student_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='main_subjects',
            field=models.ManyToManyField(default=Du_An.models.MainSubject.generate_main_subjects, related_name='student', to='Du_An.mainsubject'),
        ),
    ]
