# Generated by Django 5.1 on 2024-09-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Du_An', '0008_alter_student_main_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluateByCommentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_passed', models.BooleanField(default=None, null=True)),
                ('comment', models.TextField()),
            ],
        ),
    ]
