# Generated by Django 5.1 on 2024-09-27 13:38

import Du_An.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Du_An', '0011_remove_class_students_student_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='second_term_comment_subject',
            field=models.ManyToManyField(default=Du_An.models.EvaluateByCommentSubject.generate_comment_subject, related_name='second_term_student', to='Du_An.evaluatebycommentsubject'),
        ),
        migrations.AddField(
            model_name='student',
            name='second_term_main_subjects',
            field=models.ManyToManyField(default=Du_An.models.MainSubject.generate_main_subjects, related_name='second_term_student', to='Du_An.mainsubject'),
        ),
        migrations.AddField(
            model_name='student',
            name='second_term_second_subjects',
            field=models.ManyToManyField(default=Du_An.models.SecondSubject.generate_second_subjects, related_name='second_term_student', to='Du_An.secondsubject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='comment_subjects',
            field=models.ManyToManyField(default=Du_An.models.EvaluateByCommentSubject.generate_comment_subject, related_name='student', to='Du_An.evaluatebycommentsubject'),
        ),
    ]
