# Generated by Django 5.1 on 2024-09-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Du_An', '0012_student_second_term_comment_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondsubject',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='comment_subjects',
            field=models.ManyToManyField(related_name='student', to='Du_An.evaluatebycommentsubject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='main_subjects',
            field=models.ManyToManyField(related_name='student', to='Du_An.mainsubject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_subjects',
            field=models.ManyToManyField(related_name='student', to='Du_An.secondsubject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_term_comment_subject',
            field=models.ManyToManyField(related_name='second_term_student', to='Du_An.evaluatebycommentsubject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_term_main_subjects',
            field=models.ManyToManyField(related_name='second_term_student', to='Du_An.mainsubject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_term_second_subjects',
            field=models.ManyToManyField(related_name='second_term_student', to='Du_An.secondsubject'),
        ),
    ]
