# Generated by Django 5.1 on 2024-10-11 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Du_An', '0017_remove_student_role_studentyearprofile_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classyearprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(default='', max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentyearprofile',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Du_An.classyearprofile'),
        ),
    ]
