name: Testing
on: [push, pull_request]

jobs:
  setup:
    name: Set up environment
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        path: Du_An_KHKT
    

    - name: Set up Python 3.12
      id: python-setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Intall chromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+')
        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" || curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
        wget -N "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        rm chromedriver_linux64.zip
      



  Django_test:
    runs-on: ubuntu-latest
    needs: setup
    steps:

    - name: Run Django unit tests
      run: |
        python manage.py test Du_An
      

  Selenium_test:

    runs-on: ubuntu-latest
    needs: setup
    steps:

    - name: run Selenium tests
      run: |
        python Du_An/selenium/tests.py

