name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip install --user -r requirements.txt
        python manage.py test Du_An
        python Du_An/selenium/tests.py
        